### ISSUE TITLE
Update package dependancy for Yii2 imagine

### ISSUE THREAD

**Issue by maxodrom** [paulzi/yii2-file-behavior#1]
Приветствую!
Нельзя ли обновить зависимость вашего пакета от Yii2 imagine для работы с более стабильной и рекомендуемой версии Imagine для Yii2 (v0.6.3). 
Несколько мес. назад вышел апдейт более стабильного релиза для Yii2 imagine, которым пользуются и я и, думаю, уже многие другие разработчики, а в вашей версии зависимость указана еще как "yiisoft/yii2-imagine": "~2.0.0", что требует установки более ранней версии Yii2 imagine (v0.5.0), которая менее стабильна и не содержит последних багфиксов.

Если в вашем пакете не содержится явных жестких ограничений на версию Yii2 imagine и зависимостей от нее, то не нельзя ли сделать для вашего пакета зависимость, которая рекомендуется для пакета [Yii2 Imagine](https://github.com/yiisoft/yii2-imagine):

```text
"yiisoft/yii2-imagine": "~2.1.0"
```

В противном случае из-за вашей зависимости приходится съезжать на более раннюю и менее стабильную версию Yii2 imagine.

Проблема, которую отображает Composer:

```text
Problem 1
    - paulzi/yii2-file-behavior v1.1.2 requires yiisoft/yii2-imagine ~2.0.0 -> satisfiable by yiisoft/yii2-imagine[2.0.0, 2.0.0-beta, 2.0.0-rc, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.x-dev] but these conflict with your requirements or minimum-stability.
    - paulzi/yii2-file-behavior v1.1.1 requires yiisoft/yii2-imagine ~2.0.0 -> satisfiable by yiisoft/yii2-imagine[2.0.0, 2.0.0-beta, 2.0.0-rc, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.x-dev] but these conflict with your requirements or minimum-stability.
    - paulzi/yii2-file-behavior v1.1.0 requires yiisoft/yii2-imagine ~2.0.0 -> satisfiable by yiisoft/yii2-imagine[2.0.0, 2.0.0-beta, 2.0.0-rc, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for paulzi/yii2-file-behavior ~1.1.0 -> satisfiable by paulzi/yii2-file-behavior[v1.1.0, v1.1.1, v1.1.2].
```

**Comment by maxodrom** [comment]
Та же самая беда.
Imagine ушел уже далеко вперед, как и yii2-imagine.
Нельзя ли снова обновить зависимости уже до "yiisoft/yii2-imagine": "~2.2.0" и вычеркнуть старое "yiisoft/yii2-imagine": "~2.1.0"

**Comment by paulzi** [comment]
Ок, как будет время постараюсь вообще избавиться от зависимости от yii2-imagine

**Comment by maxodrom** [comment]
> 
> 
> Ок, как будет время постараюсь вообще избавиться от зависимости от yii2-imagine

Ждемс.

**Comment by paulzi** [comment]
Пока только добавил ~2.2.0
