### ISSUE TITLE
 PHP Recoverable Error – yii\base\ErrorException Object of class paulzi\fileBehavior\File could not be converted to string

### ISSUE THREAD

**Issue by maxodrom** [paulzi/yii2-file-behavior#2]
Есть модель UserProfile с полем image (в таблице БД) и есть конфигурация поведений (взято из примера вашего мануала):

```php
class UserProfile extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user_profile}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'timestamp' => [
                'class' => TimestampBehavior::class,
            ],
            'photoUpload' => [
                'class' => 'paulzi\fileBehavior\FileBehavior',
                'path' => '@webroot/uploads/profile',
                'url' => '@web/uploads/profile',
                'attributes' => [
                    'image' => [
                        'class' => 'paulzi\fileBehavior\Image',
                        'salt' => Yii::$app->params['appSalt'],
                        'types' => [
                            'mid' => [200, 200],
                            'thm' => [80, 80],
                        ],
                    ],
                ],
            ],
        ];
    }
```

Если я во view (форма профиля пользователя) пробую сделать так:
```php
use yii\bootstrap\ActiveForm;

$form = ActiveForm::begin([
      'layout' => 'default',
       'options' => ['enctype' => 'multipart/form-data']
 ]);

echo $form->field($model, 'image')->fileInput();

...
```

вылетает:
```txt
 PHP Recoverable Error – yii\base\ErrorException Object of class paulzi\fileBehavior\File could not be converted to string
```

Вопрос: как тогда работать с полем image модели UserProfile, если вылетает такой Exception? 
Что я делаю не так?
Как работать с этим атрибутом модели во view? Это совершенно непонятно из документации.

Далее, если уже при сохранении модели делать следующее (во view при этом исползьуется несуществующий - сэмулированный - атрибут модели под названием `photo`):
```php 
$image  = UploadedFile::getInstance($model, 'photo');
$model->image->value = $image->tempName; // из документации
$model->save();
```

будет выброшено исключение:
```
Imagine\Exception\InvalidArgumentException
Saving image in "tmp" format is not supported, please use one of the following extensions: "gif", "jpeg", "png", "wbmp", "xbm"
```
При этом файл все-таки созраняется, причем с расширением .tmp(!), а не с исходным расширением .png

В общем, создается впечатление, что данный пакет толком не работает и использование его не является прозрачным для прикладного разработчика.

**Comment by paulzi** [comment]
1) По поводу этого:
```php
echo $form->field($model, 'image')->fileInput();
```
Это вопрос к Yii-шке, что за строку она пытается поставить в поле типа `file`. К сожалению, не всё предоставляемое фреймворком удобно для использования и расширения функционала. В частности, данный behavior предоставляет функцию сохранения файлов путём замены текстового значения на объект, только благодаря этому становятся доступны такие штуки как:
```php
echo $model->image->thm->url; // доступ к URL миниатюры картинки
```
Если бы image был бы строкой, естественно такое бы не вышло.
Дальше, зачем в виджете файла получать строку с текущим значением - вопрос к Yii, но он в классическом HTML input-file-поле использоваться точно не может. Ошибку можно попробовать устранить так:
```php
echo $form->field($model, 'image')->fileInput(['value' => '']);
```

Возможно, конечно, стоило добавить немного магии в виде __toString().

2) По поводу этого:
```php
$model->image->value = $image->tempName; // из документации
```

Есть некоторые недоработки behavior-а . Поведение при сохранении файла, сохраняет его оригинальное расширение, для того, чтобы потом правильно сервер отдавал MIME-тип файла. Но в примере из документации используется `->tempName` куда PHP пишет временный путь с расширением .tmp (или вообще без расширения). Это недоработка, в том числе документации, и начиная с версии 1.2.2 доступно указание оригинального имени файла при указании:
```php
$model->image->setValue($image->tempName, true, $image->name);
```

3)

> В общем, создается впечатление, что данный пакет толком не работает и использование его не является прозрачным для прикладного разработчика.

Отчасти согласен, к сожалению, пока много времени выделить на развитие не имею, идеи есть. Но пакет рабочий, но есть ряд особенностей, которые не всегда задокументированы.

**Comment by maxodrom** [comment]
Спасибо за ваш быстрый ответ.

Конечно, документацию хотелось бы видеть актуальной, чтобы у прикладных разработчиков, использующих ваш пакет в своих проектах, возникало как можно меньше вопросов, как это произошло в моем случае.
А у меня-то, собственно, возникли элементарные вопросы, когда я уже апосля столкнулся с проблемами во View,  настроив конфиг по вашему мануалу для начала работы. Это первое.

Второе. 
> Это вопрос к Yii-шке, что за строку она пытается поставить в поле типа file. К сожалению, не всё предоставляемое фреймворком удобно для использования и расширения функционала.

Не совсем могу согласиться, что это вопрос к Yii. 
Вот классический пример аплоада файлов из гайда Yii2: https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/input-file-upload.md
Там показана рабата даже не с ActiveRecord, а с обычной \yii\base\Model. Во view я, собственно, и пытался идти по этим шагам, проделывая это на материале вашего пакета.

Если НЕ использовать обычный UploadedFile инстанс, то почему в вашем случае возникает Fatal error при конвертации объекта в строку, а в случае UploadedFile - нет, когда мы пишем такое?

```text
Object of class paulzi\fileBehavior\Image could not be converted to string
```

```php 
<?= $form->field($model, 'image')->fileInput(['accept' => 'image/*']) ?>
```

Ответ как бы очевиден: потому что UploadedFile имплементирует внутри себя магический __toString(): 
https://github.com/yiisoft/yii2/blob/master/framework/web/UploadedFile.php#L68

Вы советуете, что не было ругани сделать: 
```php
echo $form->field($model, 'image')->fileInput(['value' => '']);
```

но это больше напоминает костыль. Почему бы не реализовать такую же возможность приведения к строке ВАШЕГО объекта \paulzi\fileBehavior\Image или его родителя \paulzi\fileBehavior\File?!

Ведь если этого нет в документации, то это уже большая и не очевидная проблема, которая заставит пользователей вашего пакета лезть в исходники :)

Я понимаю вашу мысль, что вы также используете "магию" __get() и __set(), чтобы съэмулировать псевдонимы для миниатюр типа 
```php
echo $model->image->thm->url; // доступ к URL миниатюры картинки 
```

Так почему бы не продолжить дальше, и не реализовать __toString() для клиентского кода Yii2, типа BaseHtml::input(), который будет работать в вашими объектами и который требует строчного представления объекта? Возможно это решило бы проблему 
```text
Object of class paulzi\fileBehavior\Image could not be converted to string
```
И это уже не стало бы "проблемой" Yii2. 

```php
class File extends Component implements IFileAttribute
{
...
public function __toString()
{
    return $this->getValue();
}
...
}
```

или даже как-то как:
```php
class Image extends File {
public function __toString()
    {
        if ($this->getValue() instanceof UploadedFile) {
            return $this->getValue()->name;
        }
    }
}
```

Но в общем, смысл таков, что не Yii2 должен приноравливаться к условиям использования вашего пакета, а скорее наоборот, так как пакет пишется и декларируется как Yii2-behavior.

В остальном ваши идеи и реализация довольно интересны, особенно с "магией" для создания и обращения к псевдонимам превьюшек и конфигурации миниатюр, а также возможностью хранения файлов в хотя бы в элементарном дереве директорий, чего лишены другие аналогичные пакеты.

Но в заключении хотелось бы ожидать, что эти моменты будут учтены в последующем развитии, а также улучшение документации с примерами использования по классике MVC.

Спасибо. Issue можно закрывать.

**Comment by paulzi** [comment]
Да с __toString() согласен, что собственно и написал, добавлю - закрою issue.

**Comment by maxodrom** [comment]
Спасибо, ждем )
